In [16]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [42]:
# Step 3: Create a model and train it
model = LogisticRegression(solver='lbfgs', C=10, random_state=0)
model.fit(x, y)

LogisticRegression(C=10, random_state=0)

In [43]:
# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [31]:
print('x:', x, sep='\n')

x:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [32]:
print('y:', y, end='\n\n')

y: [0 1 0 0 1 1 1 1 0 1]



In [33]:
print('intercept:', model.intercept_)
print('coef:', model.coef_, end='\n\n')

intercept: [-0.28982553]
coef: [[0.19014617]]



In [44]:
score

0.7

In [24]:
print('p_pred:', p_pred, sep='\n', end='\n\n')

p_pred:
[[0.66008686 0.33991314]
 [0.60046896 0.39953104]
 [0.53771763 0.46228237]
 [0.47374812 0.52625188]
 [0.41062894 0.58937106]
 [0.35032116 0.64967884]
 [0.29444559 0.70555441]
 [0.24413314 0.75586686]
 [0.19998097 0.80001903]
 [0.16210138 0.83789862]]



In [25]:
print('y_pred:', y_pred, end='\n\n')

y_pred: [0 0 0 1 1 1 1 1 1 1]



In [40]:
print('score:', score, end='\n\n')

score: 0.7



In [27]:
print('conf_m:', conf_m, sep='\n', end='\n\n')

conf_m:
[[2 2]
 [1 5]]



In [28]:
print('report:', report, sep='\n')

report:
              precision    recall  f1-score   support

           0       0.67      0.50      0.57         4
           1       0.71      0.83      0.77         6

    accuracy                           0.70        10
   macro avg       0.69      0.67      0.67        10
weighted avg       0.70      0.70      0.69        10



In [16]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# 1. Create some simple data
#X = np.array([[1, 2], [2, 3], [3, 1], [6, 5], [7, 7], [8, 6]])
#y = np.array([0, 0, 0, 1, 1, 1])  # Binary classification (0 or 1)
X = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [22]:
# 2. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# test_size=0.3 means 30% of the data will be used for testing
# random_state ensures the split is the same each time for reproducibility

# 3. Create and train the Support Vector Machine (SVM) model
# SVC stands for Support Vector Classifier (for classification tasks)
# kernel='linear' means we're trying to find a straight line to separate the classes
# C=1.0 is the regularization parameter (similar to Logistic Regression, but with a different effect)
model = SVC(kernel='linear', C=5.0, random_state=0)
model.fit(X_train, y_train)

SVC(C=5.0, kernel='linear', random_state=0)

In [23]:
# 4. Make predictions on the test set
y_pred = model.predict(X_test)

# 5. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the SVM model: {accuracy:.2f}")

# You can also print the predictions and actual values for comparison
print("\nPredictions:", y_pred)
print("Actual labels:", y_test)

Accuracy of the SVM model: 0.33

Predictions: [1 0 1]
Actual labels: [0 1 1]
